config/routes.rb
Rails.application.routes.draw do
  resources :passwords, param: :token

  root "home#index"
  get "about" => "home#about"
  get "calendar" => "home#calendar"
  post "signup" => "registrations#create"
  get "today" => "home#today"
  get "signup" => "registrations#new"
  get "up" => "rails/health#show", as: :rails_health_check
  get "switch_lang" => "application#switch_lang"

  get "login" => "sessions#new"
  post "login"  => "sessions#create"
  get "logout"  => "sessions#destroy"

  post "day/new" => "days#create"
  get "day/delete" => "days#delete"

  get "calendar_data" => "calendar#data"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Authentication

  def index
  end
  def calendar
    @current_user = User.current
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidebar.html.erb
<%= javascript_pack_tag "sidebar" %>

<div class="absolute top-5 left-5 text-4xl cursor-pointer" id="burger">&#9776;</div>

<!-- Оверлей, затемняет остальной контент -->
<div class="fixed inset-0 bg-gray-800 bg-opacity-40 z-40 hidden" id="overlay"></div>

<div class="fixed left-0 top-0 h-full w-60 bg-white shadow-lg transform -translate-x-full transition-transform duration-300 ease-in-out z-50" id="sidebar">

  <div class="mt-5 ml-5 text-5xl cursor-pointer" id="closeSidebar">&hookleftarrow;</div>
  <div class="p-4">
    <h2 class="sidebar text-xl font-bold"><%= t('website_title') %></h2>
    <ul>
      <li class="mt-4">
        <p class="text-gray-500"><%= t("you_are_logged_in_as") %></p>
        <p class="text-gray-500"><%= User.find(Current.session.user_id).email_address %></p>
      </li>
      <li class="mt-4"><a href="/" class="text-gray-700"><%= t('today') %></a></li>
      <li class="mt-4"><a href="/calendar" class="text-gray-700"><%= t("full_calendar") %></a></li>
      <li class="mt-4"><a href="/about" class="text-gray-700"><%= t("about_link") %></a></li>
      <li class="mt-4"><%= link_to t("logout"), '/logout', class: "text-gray-700" %></a></li>
    </ul>
  </div>

  <div class="absolute bottom-0 pl-4">
    <p class="text-gray-500"><%= t("toggle_language") %></p>
    <div class="flex mt-2 w-full space-x-4">
      <%= link_to image_tag('en_flag.svg', alt: 'English', class: 'border-2 border-black'), switch_lang_path(lang: 'en'), class: "min-w-12 min-h-12" %>
      <%= link_to image_tag('ru_flag.svg', alt: 'Русский', class: 'border-2 border-black'), switch_lang_path(lang: 'ru'), class: "min-w-12 min-h-12" %>
    </div>
  </div>

</div>

app/views/home/about.html.erb
<%= render 'sidebar' %>

<div class="flex justify-center">
  <div class="mt-20 w-9/12 sm:w-7/12">
    <p class="text-center text-xl sm:text-2xl font-semibold">
      <%= t('about_first') %>
    </p>
    <p class="mt-4 sm:text-xl text-base">
      <%= t('about_second') %>
    </p>
    <p class="mt-4 sm:text-xl text-base">
      <%= t('about_third') %>
    </p>
  </div>
</div>

app/views/home/calendar.html.erb
<%= render 'sidebar' %>
<%= javascript_pack_tag "calendar" %>

<div class="p-8">
  <div class="flex flex-col justify-center items-center h-full">
    <div id="calendar"></div>
    <div class="w-auto h-auto bg-white border border-gray-300 rounded-lg shadow-md flex flex-col justify-center items-center m-4">
      <p class="m-4 font-semibold no-select text-lg text-center"><%= t("in_this_month")%></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("you_had_good_days")}: #{@current_user.get_count_good_days}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("you_had_bad_days")}: #{@current_user.get_count_bad_days}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("your_longest_white_stripe")}: #{@current_user.get_the_longest_white_stripe}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("your_longest_black_stripe")}: #{@current_user.get_the_longest_black_stripe}" %></p>
      <p class="m-4 font-semibold no-select text-lg text-center"><%= t("in_last_month") %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("you_had_good_days")}: #{@current_user.get_count_good_days_last_full_month}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("you_had_bad_days")}: #{@current_user.get_count_bad_days_last_full_month}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("your_longest_white_stripe")}: #{@current_user.get_the_longest_white_stripe_last_full_month}" %></p>
      <p class="m-4 no-select text-lg text-center"><%= "#{t("your_longest_black_stripe")}: #{@current_user.get_the_longest_black_stripe_last_full_month}" %></p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'sidebar' %>

<% if User.current.did_not_rate_this_day %>
  <%= javascript_pack_tag "swipe" %>

  <div class="flex flex-col text-3xl justify-center items-center h-1/4">
    <h1 class="mt-10"><%= t('hi') %></h1>
    <h2 class="mt-4 no-select text-lg"><%= t('how_was_your_day') %></h2>
  </div>

  <!--
  <div class="mt-4 flex justify-center items-center w-1/4 h-auto">
    <div id="swipe-hint" class="opacity-0 transition-opacity duration-500">
      <p>Hint</p>
    </div>
  </div>
  -->

  <div class="flex justify-center items-center h-1/2 z-20">
    <div class="relative no-select w-1/2 h-auto bg-white transition-transform duration-100 ease-in-out" id="swipe-widget">
      <img id="neutral-face" src="face_without_mouth.svg" class="no-select pointer-events-none absolute l-0 t-0 w-full h-auto"></img>
      <img id="sad-face" src="slightly_frowning_face.svg" class="hidden no-select pointer-events-none absolute l-0 t-0 w-full h-auto"></img>
      <img id="smiling-face" src="slightly_smiling_face.svg" class="hidden no-select pointer-events-none absolute l-0 t-0 w-full h-auto"></img>
      <img src="background.svg" class="no-select pointer-events-none w-full h-auto"></img>
    </div>
  </div>

  <div class="fullscreen pointer-events-none z-10">
    <img class="z-10 hidden no-select fixed left-0 bottom-0" id="left-gradient" src="gradient-red.png"></img>
    <img class="z-10 hidden no-select fixed right-0 bottom-0" id="right-gradient" src="gradient-green.png"></img>
  </div>
<% else %>
  <div class="flex justify-center">
    <div class="text-center mt-20 w-9/12 sm:w-7/12">
      <h1 class="text-xl"><%= t('you_already_rated_your_day') %></h1>
      <%= link_to button_tag(t('change_rating'), class: "mt-4"), '/day/delete' %>
    </div>
  </div>
<% end %>